### ISSUE TITLE
Breg remote

### ISSUE THREAD

**Issue by fendi1989** [lpBunny/bof-registry#1]
Can you please add a example of using breg remotly.the syntax of \\computername\hive\ is a little bit confusing. Thx for advance

**Comment by lpBunny** [comment]
Added an example in d435897bb1f0b4b4b252d5bfa7775b6b302d611e, you should see it in the latest commit now. The syntax `\\computername\path` is pretty standard for remote SMB access and also the syntax that `reg.exe` uses, so most registry commands should already be compatible with this bof.
